### ISSUE TITLE
R Studio/Jupyter Notebook Server

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/hackweek-2018#11]

**Comment by sr320** [comment]
https://agent-jay.github.io/2018/03/jupyterserver/

**Comment by kubu4** [comment]
R Studio server is now installed on both emu and roadrunner. Access in the following fashion:

Enter the following IP address into your browser:

For EMU enter: ```128.95.149.26:8787```

For ROADRUNNER enter: ```128.95.149.67:8787```

Use your login credentials for each respective computer.
