### ISSUE TITLE
Establish histology database, physical inventory, and management plan

### ISSUE THREAD

**Issue by sr320** [RobertsLab/hackweek-2018#13]
We should start considering how to organize things and how to document all of this stuff. It'd be killer to have links to corresponding images in the database, as well as info on post-embedding sampling info (i.e. RNA/DNA isolations).

moved from https://github.com/RobertsLab/resources/issues/213

**Comment by sr320** [comment]
https://github.com/RobertsLab/resources/wiki/Data-Management#histology-data-management-plan

**Comment by kubu4** [comment]
Beginning to parse full timestamp from file names:

Example:

```
ls -l --time-style=full-iso /mnt/owl/phainopepla/C_gigas/2016-12-05/20161205_Sample_8.raw | awk '{print $6, $7}' | tr -d "-" | tr ' ' '_' | tr -d :
```

Outputs:
```
20161208_094059.000000000
```

**Comment by kubu4** [comment]
Updated code:

```
ls -l --time-style=full-iso /mnt/owl/phainopepla/C_gigas/2016-12-05/20161205_Sample_8.raw | awk '{print $6, $7}' | tr -d - | tr -d : | cut -c 1-15
```

Output:

```
20161208 094059
```

**Comment by kubu4** [comment]
Final fix!

```
ls -l --time-style=full-iso /mnt/owl/phainopepla/C_gigas/2016-12-05/20161205_Sample_8.raw | awk '{print $6, $7}' | tr -d - | tr -d : | tr ' ' '_' | cut -c 1-15
```

Output:

```
20161208_094059
```
