### ISSUE TITLE
Document NGS/genome modifications

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/hackweek-2018#16]
A centralized resource for tracking some of the following things would be useful:

- FastQC/MultiQC data for raw NGS files

- Trimmed NGS files

- FastQC/MulitQC data for trimmed NGS files

- Genome assembly index files (e.g. Bowtie2 index files)

For NGS stuff, add to Nightingales sheet?

For genome stuff, add to wikis?

**Comment by kubu4** [comment]
This will tie into Issue #20 (canonical data management), by adding to RobertsLab/resources wiki.

**Comment by sr320** [comment]
added bulleted list to #20
