### ISSUE TITLE
figure out pull request workflow in Rstudio

### ISSUE THREAD

**Issue by sr320** [RobertsLab/hackweek-2018#19]
on repo someone is not admin on ..

**Comment by kubu4** [comment]
1. Fork desired repo.

2. Create new project in R Studio.

3. Select version control.

4. Enter GitHub info for forked repo.

5. Edit R project, commit and push changes.

6. Go to your forked repo on GitHub and initiate pull request.

**Comment by sr320** [comment]
Thanks!

**Comment by sr320** [comment]
@yaaminiv for clarification @kubu4 provided the solution; are you interested in a tutorial or ?

**Comment by yaaminiv** [comment]
@sr320 I ranked the issue without looking at the comments...I think the explanation is good enough and I personally do not need a tutorial!

**Comment by kubu4** [comment]
Maybe we should close this issue, as it is resolved?

Or, do we want to keep all issues around as talking points at the beginning of Hackweek?

**Comment by sr320** [comment]
closed, it remains present on board so we can discuss
