### ISSUE TITLE
Data Management/Workflow "Audit"

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/hackweek-2018#24]
Sounds scary!

But, it would be good to have a review of how/where data/notebooks are being backed up, evaluate presence/absence of README files, discuss workflows (e.g. how does everyone manage browser tabs??) etc.

**Comment by kubu4** [comment]
We never discussed data backup much. Specifically, how are we (are we?) backing up everyone's notebooks? Should we be running an automated script to perform weekly ```git pull``` on GitHub notebooks and saving them to Owl/Eagle or something?

Alternatively, would there be a way to move them to the RoberstLab GitHub organization instead of notebooks being hosted on personal GitHub accounts?

**Comment by sr320** [comment]
Do this at 9?

**Comment by kubu4** [comment]
Notebooks are backed up via RSS feed to genefish.wordpress.org

Set up script to regularly run ```git pull``` on other lab-related, personal repos.
