### ISSUE TITLE
Rescue info from Wikispaces

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/hackweek-2018#3]
Our old [Wikispaces](genefish.wikispaces.com) site will be shutting down in July. 

Specifically, I think there might be some lab protocol stuff that would be good to copy over to GitHub.

**Comment by sr320** [comment]
plus a few other sites....
 bio533
and more...

**Comment by sr320** [comment]
backed up olyo @ http://owl.fish.washington.edu/halfshell/bu-wikispaces/olyo/table_of_content.html

**Comment by sr320** [comment]
backup of Bio533 @ http://owl.fish.washington.edu/halfshell/bu-wikispaces/bio533/table_of_content.html

**Comment by sr320** [comment]
and genefish.

http://owl.fish.washington.edu/halfshell/bu-wikispaces/genefish/table_of_content.html
