### ISSUE TITLE
Find a file! 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/hackweek-2018#33]
Real world test of need to find a file.... 

>s, we 
referred to your genome build designated QPX_v0.1.5, and one of the 
reviewers is asking about availability of that build. We initially 
accessed it through https://bio533.wikispaces.com/QPX+Genome+Annotation  
but I understand that the server is being shut down soon. Do you have 
this build published on another database that we can refer to?

@kubu4 is aquacul4 still bootable? 

I think it is that box in conference room.

**Comment by sr320** [comment]
Found it on eagle!

![eagle](https://d.pr/i/4jJ3kp+)

**Comment by kubu4** [comment]
> @kubu4 is aquacul4 still bootable?

I'll find out!

**Comment by kubu4** [comment]
The URL on the wikispaces page (http://aquacul4.fish.washington.edu/~steven/armina/QPX_v017.fasta) suggests this is the location where this data is held.

However, when looking at Aquacul4, the ```armina``` portion is a symbolic link to ```/Volumes/AquaculX```. This does not exist on Aquacul4. Was it an external drive? Maybe that Lacie drive?

**Comment by sr320** [comment]
Probably
